# Generated by Django 4.2 on 2023-09-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_socures_location_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('lid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
