# Generated by Django 4.2 on 2024-02-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('rid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('routeway', models.CharField(max_length=150)),
            ],
        ),
    ]
