# Generated by Django 4.2 on 2024-02-09 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('BID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('BusNumber', models.CharField(max_length=255)),
                ('BusType', models.CharField(max_length=255)),
                ('DepartureTime', models.DateTimeField()),
                ('ArrivalTime', models.DateTimeField()),
                ('TotalTime', models.DurationField()),
                ('Amount', models.IntegerField()),
                ('RID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
        ),
    ]
