# Generated by Django 4.2 on 2024-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus',
        ),
    ]
