# Generated by Django 4.2 on 2024-02-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='busImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
            ],
        ),
    ]
