# Generated by Django 4.2 on 2024-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_busimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='busImage',
        ),
    ]
