# Generated by Django 4.2 on 2024-02-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_bus_busimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busimage',
            name='bid',
        ),
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='busImage',
        ),
    ]
