# Generated by Django 4.2 on 2024-03-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_bus_busimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingDropping',
            fields=[
                ('city', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('BDpoints', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
