# Generated by Django 4.2 on 2024-03-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_boardingdropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reservDate', models.DateField()),
                ('totalAmount', models.IntegerField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
