# Generated by Django 4.2 on 2024-03-12 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengerdetails',
            fields=[
                ('passengerid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('boardingPoint', models.CharField(max_length=100)),
                ('boardingAddress', models.TextField()),
                ('droppingPoint', models.CharField(max_length=100)),
                ('droppingAddress', models.TextField()),
                ('reservid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
    ]
