# Generated by Django 4.2 on 2024-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_reservation_seatassignment_passengerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkroute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routedict', models.CharField(max_length=500)),
            ],
        ),
    ]
