# Generated by Django 4.2 on 2024-03-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_checkroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkroute',
        ),
    ]
