# Generated by Django 4.2 on 2024-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_checkroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkroute',
            fields=[
                ('checkrid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('routedict', models.CharField(max_length=500)),
            ],
        ),
    ]
