# Generated by Django 4.2 on 2024-03-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_checkroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='reservid',
        ),
        migrations.DeleteModel(
            name='passengerdetails',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.DeleteModel(
            name='seatassignment',
        ),
    ]
