# Generated by Django 4.2 on 2024-03-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_reservation_seatassignment_passengerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancellation',
            fields=[
                ('cancelid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cancelAmount', models.IntegerField()),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('resverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
    ]
