# Generated by Django 4.2 on 2024-03-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerdetails',
            name='reservid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='custid',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='seatassignment',
            name='reservid',
        ),
        migrations.DeleteModel(
            name='cancellation',
        ),
        migrations.DeleteModel(
            name='passengerdetails',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.DeleteModel(
            name='seatassignment',
        ),
    ]
