# Generated by Django 4.2 on 2024-05-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_passengerdetails_reservid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reservDate', models.DateField()),
                ('totalAmount', models.IntegerField()),
                ('boardingPoint', models.CharField(max_length=100)),
                ('boardingAddress', models.TextField()),
                ('droppingPoint', models.CharField(max_length=100)),
                ('droppingAddress', models.TextField()),
                ('paymentStatus', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
        ),
        migrations.CreateModel(
            name='seatassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatnumbers', models.TextField()),
                ('reservid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='passengerdetails',
            fields=[
                ('passengerid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('reservid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='cancellation',
            fields=[
                ('cancelid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cancelAmount', models.IntegerField()),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('resverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reservation')),
            ],
        ),
    ]
